FROM jboss/wildfly:23.0.1.Final

RUN /opt/jboss/wildfly/bin/add-user.sh admin Admin#70365 --silent

ADD target/demo-metrics-hello.war /opt/jboss/wildfly/standalone/deployments/

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "--server-config", "standalone-microprofile.xml", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]