version: "3.4"
services:
  backend:
    container_name: demo-metrics-hello
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
    - "8080:8080"
    - "9990:9990"
    environment:
      - JAEGER_SERVICE_NAME=hello-service
      - JAEGER_AGENT_HOST=demo-metrics-jaeger
      - JAEGER_REPORTER_LOG_SPANS=true
      - JAEGER_REPORTER_FLUSH_INTERVAL=2000
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
  prometheus:
    container_name: demo-metrics-prometheus
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    ports:
    - "9090:9090"
  grafana:
    container_name: demo-metrics-grafana
    image: grafana/grafana:7.5.6-ubuntu
    ports:
    - "3000:3000"
  jaegertracing:
    container_name: demo-metrics-jaeger
    image: jaegertracing/all-in-one:1.22
    ports:
    - "16686:16686"
    - "6831:6831/udp"
