version: "3.4"
services:
  backend:
    container_name: demo-metrics-hello
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
    - "8080:8080"
    - "9990:9990"
  prometheus:
    container_name: demo-metrics-prometheus
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    ports:
    - "9090:9090"
  grafana:
    container_name: demo-metrics-grafana
    image: grafana/grafana:7.5.6-ubuntu
    ports:
    - "3000:3000"